config/routes.rb
Railstemplates::Application.routes.draw do

  devise_for :githubbers

  authenticate :githubber do

    resources :templates, :except => [:index, :show] do
      resources :likes, :only => [:create, :destroy]
      resources :works, :only => :create
      resources :commentaries, :only => :create
    end
    resources :gists, :only => [:new, :create]
    resources :repos, :only => [:new, :create]

    get '/dashboard' => "pages#dashboard", :as => :dashboard

  end

  resources :templates, :only => [:show, :index]
  get "/d/:id", :to => "templates#download", :as => :download
  resource :search, :only => :show

  get '/learn', :to => "pages#learn", :as => :learn
  get '/404', :to => "pages#error_404", :as => :error_404
  get '/500', :to => "pages#error_500", :as => :error_404
  get '/*fallback', :to => "pages#error_404"

  root :to => "pages#index"
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_filter :authenticate_githubber!, :load_github_from_session
  before_filter :set_github_path, :only => :create
  include TemplateCreator
  
  private
  def set_github_path
    params[:template][:source_url] = @github.raw_url rescue nil
  end
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/new.html.haml
%h1.parent-title Create a new template
#create-template.rounded-all
  %h2 Step 2
  = semantic_form_for @template, :url => repos_path do |form|
    = form.inputs do
      = form.input :title, :input_html => { :placeholder => "Your template title" }
      = form.input :description, :as => :text, :input_html => { :placeholder => "Some cool description" }
      = form.input :tag_list, :input_html => { :placeholder => "Comma separated tags" }
    = form.buttons do
      = form.submit 'Create!', :class => "rounded-all"