config/routes.rb
Railstemplates::Application.routes.draw do

  devise_for :githubbers

  authenticate :githubber do

    resources :templates, :except => [:index, :show] do
      resources :likes, :only => [:create, :destroy]
      resources :works, :only => :create
      resources :commentaries, :only => :create
    end
    resources :gists, :only => [:new, :create]
    resources :repos, :only => [:new, :create]

    get '/dashboard' => "pages#dashboard", :as => :dashboard

  end

  resources :templates, :only => [:show, :index]
  get "/d/:id", :to => "templates#download", :as => :download
  resource :search, :only => :show

  get '/learn', :to => "pages#learn", :as => :learn
  get '/404', :to => "pages#error_404", :as => :error_404
  get '/500', :to => "pages#error_500", :as => :error_404
  get '/*fallback', :to => "pages#error_404"

  root :to => "pages#index"
end

app/views/templates/_commentary.html.haml
.comment.rounded-all
  .arrow-comment
  = simple_format commentary.commentary
.comment-author.rounded-all
  .gravatar= gravatar_for commentary.githubber, 30
  .author
    .login= link_to commentary.githubber.name, "http://github.com/#{commentary.githubber.login}", :target => "_blank"
    .when= commentary.created_at.to_s(:long)

app/views/templates/_form.html.haml
= form_for @template do |f|
  -if @template.errors.any?
    #error_explanation
      %h2= "#{pluralize(@template.errors.count, "error")} prohibited this template from being saved:"
      %ul
        - @template.errors.full_messages.each do |msg|
          %li= msg

  .field  
    = f.label :title
    = f.text_field :title
    
    = f.label :gist_file
    = f.text_field :gist_file
    
    = f.label :description
    = f.text_area :description
    
  .actions
    = f.submit 'Save'

app/views/templates/_like_status.html.haml
#likes
  %h3 Popularity
  %p= like_counter(template)
  - if githubber_signed_in? && !current_githubber.liked?(template)
    .link-default.rounded-all
      = link_to 'I like it', template_likes_path(template), :method => :post, :id => 'like_button', :remote => true, "data-type" => "html"
  
  - if !githubber_signed_in?
    .link-default.rounded-all
      = link_to 'I like it', new_githubber_session_path, :id => 'like_button'
  .break

app/views/templates/_working_stats.html.haml
= image_tag "embed/icons/loader.gif", :alt => "Loading...", :title => "Loading..."
.work{:title => pluralize(template.stats[:working].first, "Vote"), :style => "width: #{ template.stats[:working].last}%;" }
.doesnt-work{ :title => pluralize(template.stats[:not_working].first, "Vote"), :style => "width: #{ template.stats[:not_working].last}%;"}

app/views/templates/edit.html.haml
%h1.parent-title Edit your template
#create-template.rounded-all
  = semantic_form_for @template, :url => template_path do |form|
    %h4
      Your template file:
      %strong=link_to @template.source_url, @template.source_url
    = form.inputs do
      = form.input :title, :input_html => { :placeholder => "Your template title" }
      = form.input :description, :as => :text, :input_html => { :placeholder => "Your template description" }
      = form.input :tag_list, :input_html => { :placeholder => "Comma separated tags" }
    = form.buttons do
      = form.submit 'Update!', :class => "rounded-all"

app/views/templates/index.html.haml
%h1.parent-title All templates
#all-templates
  %ul
    - @templates.each do |template|
      %li
        %section#left.rounded-all
          %h2= link_to template.title, template
          = simple_format template.description
        %section#right.rounded-all
          %p.download= pluralize(template.download_counter, "person has downloaded it", "people have downloaded it")
          %p.liked= pluralize(template.likes.count, "person like it", "people like it")


  = will_paginate @templates

app/views/templates/new.html.haml
%h1.parent-title Create a new template
#create-template.rounded-all
  %h2 Step 1
  = form_for @template do
    %fieldset.inputs
      %ol
        %li
          = label_tag "Gist/Github File URL"
          = text_field_tag :github_url, nil, :placeholder=> 'Paste here your gist or github URL here...'
    - if flash[:invalid]
      .invalid= flash[:invalid]
    %fieldset.buttons
      %ol
        %li= submit_tag 'Next', :class => "rounded-all"

app/views/templates/show.html.haml
- content_for :javascripts, include_javascripts(:preview)

#template-view

  // Left Column
  %section#left.rounded-all

    %h2 Code Viewer
    .holder-content
      // Template
      #source_code.loading{:'data-url' => @template.source_url}

  // Right Column
  %section#right.rounded-all
    .corner &nbsp;
    // Template's Name
    %h2
      = link_to @template.title, download_url(@template)
    .author
      by
      = link_to @template.githubber.name, "http://github.com/#{@template.githubber.login}"

    .holder-content
      - unless @template.description.blank?
        // Template's Descrition
        %p= @template.description
        .line-divisor.rounded-all
      #downloads
        %h3 Downloads
        .holder-content.rounded-all
          = link_to download_url(@template), download_url(@template)
          %span.notice Copied to Clipboard!
          #d_clip_button{ :title => "Copy to Clipboard"}

        = pluralize(@template.download_counter, "person has downloaded it", "people have downloaded it")
      .line-divisor.rounded-all
      = render :partial => 'like_status', :locals => { :template => @template }
      .line-divisor.rounded-all
      #working_status
        %h3 Did it work for you?
        %ul
          -if githubber_signed_in?
            %li
              .link-default.rounded-all= link_to 'Yes', template_works_path(@template, :work => true), :method => :POST, :id => 'work_button', :remote => true
            %li
              .holder-content.rounded-all
                = render :partial => 'working_stats', :locals => { :template => @template }
            %li
              .link-default.rounded-all= link_to "No", template_works_path(@template), :method => :POST, :id => 'not_work_button', :remote => true
          - else
            %li
              .link-default.rounded-all= link_to 'Yes', new_githubber_session_path, :id => 'work_button'
            %li
              .holder-content.rounded-all
                = render :partial => 'working_stats', :locals => { :template => @template }
            %li
              .link-default.rounded-all= link_to 'No', new_githubber_session_path, :id => 'not_work_button'
      .line-divisor.rounded-all
      .break
      #tag_list
        %h3 Tags
        = @template.tags.map { |t| link_to(t, "#") }.join(", ").html_safe
        
      .line-divisor.rounded-all
      .break

      #commentaries
        %h3 Comments
        .comments-list
          - if @template.commentaries.size > 0
            - @template.commentaries.reverse.each do |commentary|
              .commentary= render :partial => "commentary", :object => commentary
          - else
            %p.notice Be the first to comment about this template!
          
        - if current_githubber
          - semantic_form_for @commentary, :url => template_commentaries_path(@template), :remote => true, :html => { "data-type" => "html" } do |form|
            - form.inputs do
              = form.input :commentary, :label => "What you think about it?", :required => false
            - form.buttons do
              %li#commit-button
                = form.submit 'Comment!', :class => "rounded-all"
        - else
          %p
            = link_to "Log in to comment this template", new_githubber_session_path