config/routes.rb
Railstemplates::Application.routes.draw do

  devise_for :githubbers

  authenticate :githubber do

    resources :templates, :except => [:index, :show] do
      resources :likes, :only => [:create, :destroy]
      resources :works, :only => :create
      resources :commentaries, :only => :create
    end
    resources :gists, :only => [:new, :create]
    resources :repos, :only => [:new, :create]

    get '/dashboard' => "pages#dashboard", :as => :dashboard

  end

  resources :templates, :only => [:show, :index]
  get "/d/:id", :to => "templates#download", :as => :download
  resource :search, :only => :show

  get '/learn', :to => "pages#learn", :as => :learn
  get '/404', :to => "pages#error_404", :as => :error_404
  get '/500', :to => "pages#error_500", :as => :error_404
  get '/*fallback', :to => "pages#error_404"

  root :to => "pages#index"
end

app/views/shared/_current_githubber.html.haml
#current_githubber
  - if githubber.email
    = gravatar_for githubber
  %p
    Hello,
    %em= githubber.name
  = link_to "Sign out", destroy_githubber_session_path, :class => "rounded-all"

%ul#menu
  %li= link_to "Dashboard", dashboard_path, :class => "rounded-all"
  %li= link_to "Create a new template", new_template_path, :class => "rounded-all"
  %li= link_to "All templates", templates_path, :class => "rounded-all"
  %li= link_to "Learn more", learn_path, :class => "rounded-all"
  

app/views/shared/_footer.html.haml
.holder-content.rounded-all
  %p
    This project has been built by Sampa On Rails team (<a href="http://twitter.com/azisaka" target="_blank">@azisaka</a>, <a href="http://twitter.com/lucasmazza" target="_blank">@lucasmazza</a>, <a href="http://twitter.com/rlmflores" target="_blank">@rlmflores</a> and <a href="http://twitter.com/wylkon" target="_blank">@wylkon</a>) for Rails Rumble
  How many times did you saw yourself wishing for
  = link_to "beers", "http://beercheckin.r10.railsrumble.com/", :target => "_blank"
  and chicks while you were wasting time configuring Rails stuff, RSpec, Gems? Get a life!

app/views/shared/_header.html.haml
#search_box.rounded-all
  = form_tag search_path, :method => :get do
    = text_field_tag :q, nil, :placeholder=>'search for templates...'
    = submit_tag "search", :class => "search-button", :title => "Search"

.break
- if githubber_signed_in?
  = render :partial => 'shared/current_githubber', :locals => { :githubber => current_githubber }
- else
  %ul#menu
    %li= link_to "All templates", templates_path, :class => "sign-in rounded-all"
    %li= link_to "Learn more", learn_path, :class => "sign-in rounded-all"
  #current_githubber
    = link_to "Sign in using Github", githubber_oauth_authorize_url(:github), :title => "Sign in using Github", :class => "sign-in rounded-all"