config/routes.rb
Railstemplates::Application.routes.draw do

  devise_for :githubbers

  authenticate :githubber do

    resources :templates, :except => [:index, :show] do
      resources :likes, :only => [:create, :destroy]
      resources :works, :only => :create
      resources :commentaries, :only => :create
    end
    resources :gists, :only => [:new, :create]
    resources :repos, :only => [:new, :create]

    get '/dashboard' => "pages#dashboard", :as => :dashboard

  end

  resources :templates, :only => [:show, :index]
  get "/d/:id", :to => "templates#download", :as => :download
  resource :search, :only => :show

  get '/learn', :to => "pages#learn", :as => :learn
  get '/404', :to => "pages#error_404", :as => :error_404
  get '/500', :to => "pages#error_500", :as => :error_404
  get '/*fallback', :to => "pages#error_404"

  root :to => "pages#index"
end

app/views/pages/dashboard.html.haml
%section#left
  - if current_githubber.likes.size > 0 or current_githubber.templates.size > 0
    - if current_githubber.templates.size > 0
      #my-templates.rounded-all.textbox
        %h2 # My Templates
        %ul
          - current_githubber.templates.each do |template|
            %li{ :class => cycle( "one", "two")}
              %table
                %tr
                  %td.name-template= link_to template.title, template
                  %td= link_to 'Edit', edit_template_path(template), :class => "edit-template"
                  %td= link_to 'Delete', template_path(template), :method => :delete, :remote => true, :class => "delete-template", :confirm => "Are you sure? There's no undo!"
        .break
    - if current_githubber.likes.size > 0
      - reset_cycle
      #liked.rounded-all.textbox
        %h2 # Favorite templates
        %ul
          - current_githubber.likes.each do |like|
            %li{ :class => cycle( "one", "two")}
              %table
                %tr
                  %td.name-template= link_to like.template.title, like.template
                  %td.option= link_to "Unlike it", template_like_path(like.template, like), :class => "unlike-template", :method => :delete, :remote => true, :confirm => "Are you sure?"
                  
    #getting-started.rounded-all.textbox{ :style => "display: none" }
      %h2 # Getting started
      %p You don't have any templates yet. 
      %p 
        There are two ways to begin: 
        %ol
          %li= link_to "Create a new template", new_template_path
          %li Search for someones using our search box at the top of the page and "like" the ones you enjoy.

                  
  - else
    #getting-started.rounded-all.textbox
      %h2 # Getting started
      %p You don't have any templates yet. 
      %p 
        There are two ways to begin: 
        %ol
          %li= link_to "Create a new template", new_template_path
          %li Search for someones using our search box at the top of the page and "like" the ones you enjoy.
            
%section#right
  = link_to "Create a new template", new_template_path, :class => "link-default rounded-all"

app/views/pages/error_404.html.haml
#error.rounded-all
  .home-message
    %h1 Dude, what are you doing here? Are you lost?
    %p Try to search something at the top of this page or click on our logo to check out some awesome templates for your project.

app/views/pages/error_500.html.haml
#error.rounded-all
  .home-message
    %h1 Yeah, we are doing something wrong here.
    %p.other-error We are calling our trainees to fix it! Try again later!

app/views/pages/index.html.haml
#holder-home.rounded-all
  .home-message
    %h1.replacement Take a shortcut to your templates
    %h2.replacement Find the best to kick off your project

#explanation.rounded-all
  .home-message
    %p Share, find and rate. Participate with other developers to build and customize the best templates for your Rails apps.

#latest.rounded-all
  %h2 # Latest templates
  %ul
    - @latest.each do |template|
      %li{ :class => cycle( "one", "two")}
        = link_to template.title, template
        %p.hours= time_ago_in_words(template.created_at) + " ago"

- reset_cycle
#ranked.rounded-all
  %h2 # Most Liked
  %ul
    - @ranked.each do |ranked|
      %li{ :class => cycle( "one", "two")}
        = link_to ranked.title, ranked
        %p.liked= pluralize(ranked.likes.count, "person like it", "people like it")

app/views/pages/learn.html.haml
%h1.parent-title Rails templates learning center
#create-template.rounded-all.textbox
  %p
    We haven't wrote any tutorial yet on how to create a template, but check
    = link_to "this awesome blog post", "http://m.onkey.org/2008/12/4/rails-templates", :target => "_blank"
    from
    = link_to "Pratik Naik", "http://m.onkey.org/", :target => "_blank"
    that gives you some knowledge about how to create a Ruby on Rails application template.

  %p
    You can also check some examples extracted from github:

  %ul
    %li= link_to "A template from Diego Carrion", "http://github.com/dcrec1/rails3_template", :target => "_blank"
    %li= link_to "A template from Daniel Lopes", "http://github.com/danielvlopes/base_app", :target => "_blank"
    %li= link_to "A template from this website creators Lucas Mazza and Rodrigo Flores", "http://github.com/sabbre/base-template", :target => "_blank"